GET http://localhost:3000/blocks


###

POST http://localhost:3000/blocks
Content-Type: application/json

###

POST http://localhost:3000/peers
Content-Type: application/json

{
    "peer": "ws://localhost:4000"
}


###

GET http://localhost:3000/me/balance


###

POST http://localhost:3000/transactions
Content-Type: application/json

{
    "address": "04713677381ed0b78b2b08c02cdf83af435f3fb3f9db2bd215a588add9555d196f08c642102ff677c8cda5625092aaafdbafc0d4bea38a7076e25eca8c9bc79fdb",
    "amount": 10
}
